### ISSUE TITLE
Jupyter terminal workdir  maybe uncorrect

### ISSUE THREAD

**Issue by zTaoplus** [ZJUICI/jupyter-images#2]
When I create a notebook and open the terminal from the root directory, the current path is: `/run/s6/legacy-services/code-server`. 

However, when I open the terminal within a newly created directory, the current path is `~/folder-name`, and this works fine. 

I believe that when opening the terminal from the root directory, it should be in the current user directory `~`, which would be more accurate.

**Comment by edwardzjl** [comment]
Resolved in [6ac9477](https://github.com/ZJUICI/jupyter-images/commit/6ac947795e70e62da12befd0c16939f81bc1bbd8)
